export const mockOffers = [
  {
    name: "Help 1",
    description:
      "Volunteers are individuals who freely offer their time, labor, and expertise. Volunteers often work for schools or NGOs, where they typically receive training and report to designated senior staff. Completely free trial, no card required.",
    volunteer: "Eu",
    category: "Food",
    location: "Bacau",
    remainingOffers: 5,
    date: "25-12-2022",
  },
  {
    name: "Help 11",
    description: "",
    volunteer: "Eu",
    category: "Food",
    location: "Bacau",
    remainingOffers: 5,
    date: "25-12-2022",
  },
  {
    name: "Help 111",
    description: "",
    volunteer: "Eu",
    category: "Money",
    location: "Bacau",
    remainingOffers: 5,
    date: "25-12-2022",
  },
  {
    name: "Help 2",
    description: "",
    volunteer: "Tu",
    category: "Money",
    location: "Bucuresti",
    remainingOffers: 5,
    date: "25-12-2022",
  },
  {
    name: "Help 3",
    description: "",
    volunteer: "Noi",
    category: "Money",
    location: "Suceava",
    remainingOffers: 5,
    date: "25-12-2022",
  },
  {
    name: "Help 4",
    description: "",
    volunteer: "Voi",
    category: "Money",
    location: "Brasov",
    remainingOffers: 5,
    date: "25-12-2022",
  },
  {
    name: "Help 5",
    description: "",
    volunteer: "El",
    category: "Money",
    location: "Bucuresti",
    remainingOffers: 5,
    date: "25-12-2022",
  },
  {
    name: "Help 6",
    description: "",
    volunteer: "Ea",
    category: "Money",
    location: "Craiova",
    remainingOffers: 5,
    date: "25-12-2022",
  },
  {
    name: "Help 7",
    description: "",
    volunteer: "Ele",
    category: "Food",
    location: "Constanta",
    remainingOffers: 5,
    date: "25-12-2022",
  },
  {
    name: "Help 8",
    description: "",
    volunteer: "Ei",
    category: "Accomodation",
    location: "Cluj",
    remainingOffers: 5,
    date: "25-12-2022",
  },
];
