// Name generator: https://www.behindthename.com/random/random.php?gender=both&number=2&sets=1&surname=&usage_rmn=1
export const mockOffers = [
  {
    name: "Help 1",
    description:
      "Volunteers are individuals who freely offer their time, labor, and expertise. Volunteers often work for schools or NGOs, where they typically receive training and report to designated senior staff. Completely free trial, no card required.",
    volunteer: "Emanuel Ambroise",
    category: "Food",
    location: "Bacau",
    remainingOffers: 5,
    date: new Date("2022-05-01"),
  },
  {
    name: "Help 11",
    description: "",
    volunteer: "Judith Marcel",
    category: "Food",
    location: "Bacau",
    remainingOffers: 5,
    date: new Date("2022-05-20"),
  },
  {
    name: "Help 111",
    description: "",
    volunteer: "Robin Fulvio",
    category: "Money",
    location: "Bacau",
    remainingOffers: 5,
    date: new Date("2020-04-05"),
  },
  {
    name: "Help 2",
    description: "",
    volunteer: "Gianmarco Colombo",
    category: "Money",
    location: "Bucuresti",
    remainingOffers: 5,
    date: new Date("2020-04-05"),
  },
  {
    name: "Help 3",
    description: "",
    volunteer: "Marie-Françoise Serafina",
    category: "Money",
    location: "Suceava",
    remainingOffers: 5,
    date: new Date("2020-04-02"),
  },
  {
    name: "Help 4",
    description: "",
    volunteer: "Marie-Françoise Serafina",
    category: "Money",
    location: "Brasov",
    remainingOffers: 5,
    date: new Date("2022-05-05"),
  },
  {
    name: "Help 5",
    description: "",
    volunteer: "Sara Sandu",
    category: "Money",
    location: "Bucuresti",
    remainingOffers: 5,
    date: new Date("2022-05-05"),
  },
  {
    name: "Help 6",
    description: "",
    volunteer: "Delia Catrinel",
    category: "Money",
    location: "Craiova",
    remainingOffers: 5,
    date: new Date("2022-05-06"),
  },
  {
    name: "Help 7",
    description: "Tereza Denisa",
    volunteer: "Marie-Françoise Serafina",
    category: "Food",
    location: "Constanta",
    remainingOffers: 5,
    date: new Date("2022-05-07"),
  },
  {
    name: "Help 8",
    description: "",
    volunteer: "Marie-Françoise Serafina",
    category: "Accomodation",
    location: "Cluj",
    remainingOffers: 5,
    date: new Date("2022-05-04"),
  },
];
