version: '3.7'
services:
  postgres:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      DB_PORT: '5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    hostname: postgres
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 700M
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/sql/createTables.sql:/docker-entrypoint-initdb.d/createTables.sql  # copy the sql script to create tables
    networks:
      - db
      - app-network

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: 'admin@admin.com'
      PGADMIN_DEFAULT_PASSWORD: 'root'
    ports:
      - "5050:80"
    networks:
      - db

  server:
    environment:
      API_PORT: '5001'
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    depends_on:
      - postgres
    links:
      - postgres
    image: server:latest
    deploy:
      resources:
        limits:
          memory: 700M
    container_name: server
    hostname: server
    ports:
      - "5001:5001"
    networks:
      - app-network

  client:
    environment:
      PORT: '3000'
    depends_on:
      - postgres
    links:
      - postgres
    image: client:latest
    container_name: client
    hostname: client
    ports:
      - "3000:3000"
    networks:
      - app-network

volumes:
  postgres-data: {}

networks:
  db:
    name: 'db-network'
  app-network:
    name: 'app-network'

