version: '3.7'
services:
  postgres:
    image: postgres:11.2-alpine
    restart: always
    environment:
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
      DB_PORT: '5432'
    logging:
      options:
        max-size: 10m
        max-file: "3"
    hostname: postgres
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          memory: 700M
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./server/sql/createTables.sql:/docker-entrypoint-initdb.d/createTables.sql  # copy the sql script to create tables
    networks:
      - app-network

  server:
    environment:
      API_PORT: '5001'
      POSTGRES_DB: 'postgres'
      POSTGRES_USER: 'postgres'
      POSTGRES_PASSWORD: 'postgres'
    depends_on:
      - postgres
    image: server:latest
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
        loki-external-labels: job=server,environment=development
    deploy:
      resources:
        limits:
          memory: 700M
    container_name: server
    hostname: server
    ports:
      - "5001:5001"
    networks:
      - app-network
      - rmq
      - internal
      - logging

  client:
    environment:
      PORT: '4000'
    depends_on:
      - postgres
    links:
      - postgres
    image: client:latest
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
        loki-external-labels: job=client,environment=development
    container_name: client
    hostname: client
    ports:
      - "4000:4000"
    networks:
      - app-network
      - internal
      - logging

  rabbitmq:
    image: rabbitmq:management-alpine
    ports:
      - "5672:5672"
      - "15672:15672"
    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - rmq
    hostname: rabbitmq

  rabbitmq-worker:
    image: rabbitmq-worker
    logging:
      driver: loki
      options:
        loki-url: http://host.docker.internal:3100/loki/api/v1/push
        loki-external-labels: job=emailworker,environment=development
    restart: always
    depends_on:
      - rabbitmq
    deploy:
      resources:
        limits:
          memory: 300M
    networks:
      - rmq
      - logging

  kong:
    image: kong:latest
    volumes:
      - ./configs/kong:/usr/local/kong/declarative #injectarea fisierului de configurare la calea specificata
    environment:
      KONG_DATABASE: 'off' #obligatoriu, daca se vrea modul DB-less
      KONG_DECLARATIVE_CONFIG: /usr/local/kong/declarative/kong-config.yml #trebuie specificat unde anume se va gasi fisierul de configuyrare
      KONG_PROXY_ACCESS_LOG: /dev/stdout
      KONG_ADMIN_ACCESS_LOG: /dev/stdout
      KONG_PROXY_ERROR_LOG: /dev/stderr
      KONG_ADMIN_ERROR_LOG: /dev/stderr
      KONG_ADMIN_LISTEN: 0.0.0.0:8001, 0.0.0.0:8444 ssl
    ports:
      - "80:8000"
      - "8443:8443"
      - "8444:8444"
      - "8001:8001"
    deploy:
      placement:
        constraints: [ node.role == manager ]
    networks:
     - internal

  # docker plugin install grafana/loki-docker-driver:latest --alias loki --grant-all-permissions
  loki:
    image: grafana/loki
    volumes:
      - ./configs/loki.yml:/etc/config/loki.yml
      - ./configs/wal:/wal
    entrypoint:
      - /usr/bin/loki
      - -config.file=/etc/config/loki.yml
    ports:
      - "3100:3100"
    networks:
      - logging
      - visualizing

  grafana:
    image: grafana/grafana
    volumes:
      - grafana-volume:/var/lib/grafana
      - ./configs/grafana/provisioning:/etc/grafana/provisioning/
      - ./configs/grafana/dashboards:/var/lib/grafana/dashboards
    ports:
      - "3000:3000"
    depends_on:
      - loki
    deploy:
      placement:
        constraints: [node.role == manager]
    networks:
      - visualizing

volumes:
  postgres-data: {}
  grafana-volume: {}

networks:
  app-network:
    name: 'app-network'
  rmq:
    name: 'rabbitmq'
  internal:
    name: 'internal'
  logging:
    name: 'logging'
  visualizing:
    name: 'visualizing'
