version: '3.7'
services:
  postgres:
    image: postgres:11.2-alpine
    restart: always
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USER}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    logging:
      options:
        max-size: 10m
        max-file: "3"
    expose:
      - "${DB_PORT}"
    ports:
      - '${DB_PORT}:${DB_PORT_TARGET}'
    volumes:
      - postgres-data:/var/lib/postgresql/data
      - ./sql/createTables.sql:/docker-entrypoint-initdb.d/createTables.sql  # copy the sql script to create tables
    networks:
      - db

  pgadmin:
    image: dpage/pgadmin4
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PG_ADMIN_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PG_ADMIN_PASSWORD}
    ports:
      - "5050:80"
    networks:
      - db

volumes:
  postgres-data: {}

networks:
  db:
    name: 'db-network'