_format_version: "2.1"

services:
  - name: server
    url: http://server:5001/api
    routes:
      - name: server-route
        paths:
          - /api

plugins:
  - name: cors
    service: server
    config:
      origins:
        - "*"
